customer/urls.py
"""
    Customer urls
"""
# from django.conf.urls.defaults import url, patterns
from django.conf.urls import include, url
# from project_management.customer import views as customer_views
from project_management.customer.views import *

uuid_regex = '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'
urlpatterns = [
    url(r'^$', list_customer),
    url(r'^list/', clientlist),
    url(r'^create/', manage_client),
    url(r'^update/(?P<id>\d+)/$', manage_client),
    url(r'^deactivate/$', manage_client_status,
                {'is_active': False}, "deactivate-client"),
    url(r'^activate/$', manage_client_status,
                {'is_active': True}, "activate-client"),
    #url(r'^create/$', manage_customer_from_project, name="create_customer"),
    #url(r'^update/(?P<id>\d+)/$', manage_customer_from_project,
                                     #name="update_customer"),
    url(r'^contact/create/$', manage_customer_contact_from_project,
                                     name="create_customer_contact"),
    url(r'^contact/update/(?P<id>\d+)/$', manage_customer_contact_from_project,
                                     name="update_customer_contact")
#    url(r'^delete/(?P<id>%s)/$'%(uuid_regex), delete_customer),
]

tasks/urls.py
"""
    Url for the task application
"""
# from django.conf.urls.defaults import patterns
from django.conf.urls import include, url
from project_management.tasks import views as tasks_views
from project_management.tasks.views import *


urlpatterns = [
    url(r'^$', manage_task),
    url(r'^save/$', manage_task),
    url(r'^(?P<tid>\d+)/$', manage_task),
    url(r'^list/$', task_list),
    url(r'^list/(?P<page>\d+)/$', task_list),
    url(r'^create_type/$', manage_type),
    url(r'^manage_type/(?P<id>\d+)/$', manage_type),
    url(r'^delete_type/(?P<id>\d+)/$', delete_task_type),
    url(r'^getsubtype/$', get_sub_type),
    url(r'^delete/$', delete_task,
        { 'is_project_task': True }, "project-task-delete"),
    url(r'^nonproject/delete/$', delete_task,
        { 'is_project_task': False }, "non-project-task-delete"),
    url(r'^nonproject/create/$', manage_non_project_task),
    url(r'^nonproject/update/(?P<id>\d+)/$', manage_non_project_task),
    url(r'^nonproject/list/$', non_project_task_list),
]

urls.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
# from django.conf.urls.defaults import *
# from django.conf.urls import url, include
from django.views.generic.list import ListView
#from django.conf.urls import *
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import logout

# from django.views.generic import list_detail
# from django.views.generic.simple import TemplateView.as_view RedirectView
from django.views.generic import TemplateView
from django.views.generic import RedirectView

from project_management.users.models import UserProfile
from project_management.users.views import login
from django.contrib.auth import views as auth_views

from project_management.projectbudget.models import *
from project_management.projectbudget.budgetmasters import *
from django.conf.urls import include, url

import os.path
import django_cron

admin.autodiscover()

try:
    django_cron.autodiscover()
except BaseException:
    pass


from project_management.common_manager import views as common_manager_views
# from project_management.logs import views as logs_views
from project_management.logs.views import DisplayLog, DisplayLogData, GetLog
# from project_management.notifications import eventviews as notifications_eventviews
from project_management.notifications.eventviews import *
from project_management.repository.views import *
from project_management.non_project_task.views import *
from project_management.Utility import getPopUpDetails
from project_management.common_manager.views import *
# from project_management.projectbudget.views import *
from project_management.projects import views as projects_views
from project_management.repository import views as repository_views
from project_management.non_project_task import views as non_project_task_views
# from django.core.context_processors import csrf
from django.views.i18n import *
# from project_management.i18nDate import javascript_catalog
from project_management.i18nDate import *

import os.path
import django_cron

admin.autodiscover()

try:
    django_cron.autodiscover()
except:
    pass


# for the calender(datepicker) widget

urlpatterns = [
    # url(r'^jsi18n/$','project_management.i18nDate.javascript_catalog',{'packages': 'django.conf'}),
    url(r'^jsi18n/$',javascript_catalog,{'packages': 'django.conf'}),

]


js_info_dict = {'packages': ('cui.translations',), }

urlpatterns += [
    # url(r'^django-jsi18n/$',django.views.i18n.javascript_catalog, js_info_dict),
    url(r'^django-jsi18n/$',javascript_catalog, js_info_dict),

   
]
                        

urlpatterns = [
    # url(r'^django-jsi18n/$',javascript_catalog, js_info_dict),
    # url(r'^jsi18n/$',javascript_catalog,{'packages': 'django.conf'}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', login, {'template_name': 'login.html'}),
    url(r'^comingsoon/$', TemplateView.as_view(template_name = 'coming_soon.html')),
    url(r'^recentupdates/$', TemplateView.as_view(template_name = 'Recent_updates.html')),
    url(r'^re-use/$', TemplateView.as_view(template_name = 're-use.html')),
    url(r'^re-use/components/$', TemplateView.as_view(template_name = 'Re-Use_Library.html')),
    url(r'^5GPal/$', TemplateView.as_view(template_name = '5G-Pal.html')),
    url(r'^5GPal/Policies/$', TemplateView.as_view(template_name = '5gpal_Policies.html')),
    url(r'^5GPal/FxCop_and_Rules/$', TemplateView.as_view(template_name = '5gpal_FxCop_and_Rules.html')),
    url(r'^5GPal/Process-templates/$', TemplateView.as_view(template_name = '5gpal__process-templates.html')),
    url(r'^Mindshare/', RedirectView, {'url': '/login/'}),
    url(r'^logout/$', logout, {'template_name': 'logout.html'}),
    # url(r'^contacts/$', login_required.as_view(),{'queryset': UserProfile.objects.exclude(user__is_active=False).exclude(
    #                          user__is_staff=True).order_by('user__username'),
    #                         'template_name': 'contacts.html'}),
    url(r'^contacts/$', login_required(TemplateView.as_view(template_name='contacts.html'))),
    
]   

urlpatterns += [

    url(r'^Logs/', DisplayLog),
    url(r'^admin.ShowLog/', DisplayLogData),
    url(r'^GetLogDetail/',GetLog),
]

urlpatterns += [

    url(r'^user/', include('project_management.users.urls')),
    url(r'^project/', include('project_management.projects.urls')),
    url(r'^projectbudget/', include('project_management.projectbudget.urls')),
    url(r'^alert/', include('project_management.alert.urls')),
    url(r'^customer/', include('project_management.customer.urls')),
    url(r'^task/', include('project_management.tasks.urls')),
    url(r'^milestone/', include('project_management.milestone.urls')),
    url(r'^businessunit/', include('project_management.business_unit.urls')),
    url(r'^event/', include('project_management.notifications.urls')),
    url(r'^announcement/', include('announcements.urls')),

    # url(r'^client_visit_report/', include('project_management.client_visit_report.urls')),

    url(r'^timesheet/', include('project_management.timesheet.urls')),
    url(r'^timesheetnew/', include('project_management.timesheetnew.urls')),
    url(r'^NewsLetter/', include('newsletter.urls')),
    url(r'^conferenceroombooking/', include('project_management.conferenceroombooking.urls')),
    url(r'^codereview/', include('project_management.code_review.urls')),

    # url(r'^codereview/', include('project_management.code_review.urls', urlnamespace="codereview")),
    #url(r'^library/',include('project_management.library.urls')),
    # url(r'^comments/', include('comments.urls', namespace='comments')),
]


urlpatterns += [
    url(r'^MonthlyCalendar/$', MonthlyCalendar),
    url(r'^WeeklyCalendar/$', WeeklyCalendar),
    url(r'^DayCalendar/$', DayCalendar),
    url(r'^previousyear/(?P<type>\w+)/', previousyear),
    url(r'^nextyear/(?P<type>\w+)/', nextyear),
    url(r'^previousmonth/', previousmonth),
    url(r'^nextmonth/', nextmonth),
    url(r'^nextday/', nextday),
    url(r'^previousday/', previousday),
    url(r'^nextweek/', nextweek),
    url(r'^previousweek/', previousweek),
    url(r'^Event/', Events),
    url(r'^CreateEvent/', Events),
    url(r'^SaveEvent/', saveEvent),
    url(r'^Eventdelete/', eventDelete),
    url(r'^UpdateEvent/', updateEvent),
    url(r'^EventAccess/', accessEvent),
    url(r'^GetStage/', getStage),
]


urlpatterns += [


    url(r'^prog_task_in_pg/$', TemplateView.as_view(template_name = "prog_task_in_pg.html"), name="prog_task_in_pg"),
]

urlpatterns += [

    url(r'^repository/', RepositoryView),
    url(r'^repositoryUpload/', RepositoryUpload),
]


urlpatterns += [

    url(r'^SaveNonProjectTask/', SaveNonProjectTask),
    url(r'^SaveAndContinueNonProjectTask/', SaveAndContinueNonProjectTask),
 ]

urlpatterns += [


    url(r'^GetPopUpDetails/', getPopUpDetails),
]

urlpatterns += [

    url(r'^MasterView/', MasterView),
    url(r'^MasterSave/', MasterSave),
    url(r'^MasterDelete/', MasterDelete),

]













# to load the static data
# if settings.DEBUG:
# urlpatterns.append = [
#     url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(settings.PROJECT_ROOT, "media")}),
# ]


# urlpatterns.append = [
#     # url(r'^Logs/', 'logs_views.DisplayLog'),
#     # url(r'^admin.ShowLog/', 'logs_views.DisplayLogData'),
#     # url(r'^GetLogDetail/', 'logs_views.GetLog'),
#     url(r'^Logs/', DisplayLog),
#     url(r'^admin.ShowLog/', DisplayLogData),
#     url(r'^GetLogDetail/',GetLog),
# ]


# urlpatterns.append = [
#     url(r'^user/', include('project_management.users.urls')),
#     url(r'^project/', include('project_management.projects.urls')),
#     url(r'^projectbudget/', include('project_management.projectbudget.urls')),
#     url(r'^alert/', include('project_management.alert.urls')),
#     url(r'^customer/', include('project_management.customer.urls')),
#     url(r'^task/', include('project_management.tasks.urls')),
#     url(r'^milestone/', include('project_management.milestone.urls')),
#     url(r'^businessunit/', include('project_management.business_unit.urls')),
#     url(r'^event/', include('project_management.notifications.urls')),
#     url(r'^announcement/', include('announcements.urls')),

#     # url(r'^client_visit_report/', include('project_management.client_visit_report.urls')),

#     url(r'^timesheet/', include('project_management.timesheet.urls')),
#     url(r'^timesheetnew/', include('project_management.timesheetnew.urls')),
#     url(r'^NewsLetter/', include('newsletter.urls')),
#     url(r'^conferenceroombooking/', include('project_management.conferenceroombooking.urls')),
#     url(r'^codereview/', include('project_management.code_review.urls', urlnamespace="codereview")),
#     #url(r'^library/',include('project_management.library.urls')),
# ]


# urlpatterns.append = [
#     url(r'^MonthlyCalendar/$', 'notifications_eventviews.MonthlyCalendar'),
#     url(r'^WeeklyCalendar/$', 'notifications_eventviews.WeeklyCalendar'),
#     url(r'^DayCalendar/$', 'notifications_eventviews.DayCalendar'),
#     url(r'^previousyear/(?P<type>\w+)/', 'notifications_eventviews.previousyear'),
#     url(r'^nextyear/(?P<type>\w+)/', 'notifications_eventviews.nextyear'),
#     url(r'^previousmonth/', 'notifications_eventviews.previousmonth'),
#     url(r'^nextmonth/', 'notifications_eventviews.nextmonth'),
#     url(r'^nextday/', 'notifications_eventviews.nextday'),
#     url(r'^previousday/', 'notifications_eventviews.previousday'),
#     url(r'^nextweek/', 'notifications_eventviews.nextweek'),
#     url(r'^previousweek/', 'notifications_eventviews.previousweek'),
#     url(r'^Event/', 'notifications_eventviews.Events'),
#     url(r'^CreateEvent/', 'notifications_eventviews.Events'),
#     url(r'^SaveEvent/', 'notifications_eventviews.saveEvent'),
#     url(r'^Eventdelete/', 'notifications_eventviews.eventDelete'),

users/urls.py
"""
    urls required the user application.
"""

# from django.conf.urls.defaults import patterns
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.views.generic import RedirectView
# from project_management.users import views as users_views
from project_management.users.views import *


urlpatterns = [
    url(r'^create/$', manage_user),
    url(r'^update/(?P<pid>\d+)/$', manage_user),
    url(r'^list/$', user_list),
    url(r'^deactivate/$', manage_user_status,
                {'status': False}, "deactivate-user"),
    url(r'^activate/$', manage_user_status,
                {'status': True}, "activate-user"),
    url(r'^myprofile/$', manage_myprofile),
    
]

announcements/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from datetime import datetime

class Announcement(models.Model):
    announcement_ID = models.AutoField(primary_key = True)
    title = models.CharField(max_length = 120)
    content = models.TextField(blank=True, null=True)
    creation_date = models.DateTimeField(null = True,  blank = True,
                                                default=datetime.now)
    approved_by = models.ForeignKey(User, 
        related_name = "%(app_label)s_%(class)s_approved_by", null = True )
    is_approved = models.BooleanField(default = False)
    is_rejected = models.BooleanField(default = False)
    requested_by = models.ForeignKey(User,
        related_name = "%(app_label)s_%(class)s_requested_by", null = True)

    def __unicode__(self):
        return self.title

business_unit/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from project_management.address.models import Address

class BusinessUnitType(models.Model):
    name =  models.CharField(_('Name'), max_length = 120 )

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('Business Unit Type')
        verbose_name_plural = _('Business Unit Types')
        ordering = ['name']

class BusinessUnit(models.Model):
    name = models.CharField(_('Name'), max_length = 120)
    firstname = models.CharField(_('FirstName'), max_length = 50)
    lastname =  models.CharField(_('LastName'), max_length = 50, null = True, blank = True)
    type = models.ForeignKey(BusinessUnitType, verbose_name = _('Type'))
    address = models.ForeignKey(Address, verbose_name = _('Address'),
                                                null=True, blank=True)
    related_to = models.ForeignKey('self', null = True,  blank = True,
                                                verbose_name = _('Business Unit'))
    url = models.CharField( _('Url'), max_length = 120, null = True,  blank = True)
    cancel = models.BooleanField(_('Cancel'), default = False)
    customer_code = models.CharField(_('Code'), max_length = 20 , null = True, blank = True)
    contact_email = models.EmailField(_('Email'), null = True, blank = True)
    notes = models.TextField(_('Notes'), null = True,  blank = True )
    is_active = models.BooleanField(default = True)
    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            if BusinessUnit.objects.aggregate( models.Max('id'))['id__max'] != None:
                self.customer_code = BusinessUnit.objects.aggregate(
                        models.Max('id'))['id__max']+1
            else:
                self.customer_code = 1
            print  self.customer_code
            self.customer_code = 'C00' + str(self.customer_code)
            print self.customer_code
            
        super(BusinessUnit, self).save(**kwargs)
        
    class Meta:
        verbose_name = _('Business Unit')
        verbose_name_plural = _('Business Units')
        ordering = ['name']
        
    

business_unit/forms.py
"""
    Business Unit forms
"""
from django import forms

from project_management.business_unit.models import BusinessUnit, \
                                                BusinessUnitType

class BusinessUnitForm(forms.ModelForm):
    """
        form which represents the business unit.
    """
    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        self.fields['type'].queryset = BusinessUnitType.objects.exclude(name
                                                                = 'Customer')

    def save(self, address, commit = True):
        business_unit = super(BusinessUnitForm, self).save(commit = False)
        business_unit.address = address
        business_unit.related_to = BusinessUnit.objects.get(pk = '1')
        if commit:
            business_unit.save()
        return business_unit

    class Meta:
        model = BusinessUnit
        exclude = ('cancel', 'address', 'related_to', 'customer_code', 'firstname', 'lastname', 'contact_email', 'is_active')

templates/Announcement_List.html
{% extends "base.html" %}
{% block header-section %}
   {% include 'search_header.html' %}
{% endblock %}
{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="/static/css/base.css" title="standard-css1" />
    <link href="/static/css/forms.css" rel="stylesheet" type="text/css" />
{% endblock %}
{% block script %}
    <script type="application/javascript" language="JavaScript" src="/static/js/Validation.js"></script>
    <script type="application/javascript" src="/static/js/jquery-1.3.2.min.js"></script>
{% endblock %}
{% block title %} All Announcements {% endblock %}
{% block programcontent %} {% endblock %}
{% block programmenu %} {% endblock %}
{% block taskmenus %} {% endblock %}
{% block contentdata %}
<script type="application/javascript">
	function setRedirection(action){
	var formObj = document.getElementById("listAnnouncement");
	var newAttr = document.createAttribute("action");
	newAttr.nodeValue = action;	
	formObj.removeAttributeNode(formObj.getAttributeNode("action"));
	formObj.setAttributeNode(newAttr);
}

function fromToDateCheck(mydate1,mydate2){    
  var valid = false;
    if (Date.parse(mydate1) > Date.parse(mydate2)) {				
		$('.imgClass').hide();
		      
        }
		
}
$(document).ready(function(){


//var selObj = document.getElementById('id_createddate');
//  for (var i=0; i<document.getElementById('id_createddate').options.length; i++) {
//    //selObj.options[i].selected = true;
//	mydate1 = new Date(selObj.options[i].value);
//	var date1 = new Date(mydate1.getMonth()+"/"+mydate1.getDate()+"/"+mydate1.getFullYear());
//	alert(date1);
//	var date2 = new Date((mydate1.getMonth()+1)+"/"+mydate1.getDate((mydate1.setDate(mydate1.getDate()+2)))+"/"+mydate1.getFullYear());
//	alert(date2);
//	alert(selObj.options[i].value);
//	fromToDateCheck(date1,date2);
 

// mydate1 = new Date($('#hdn1_announcement_date').val());
//
//var date1 = new Date(mydate1.getMonth()+"/"+mydate1.getDate()+"/"+mydate1.getFullYear());
//
////s = mydate1.setDate(mydate1.getDate()+2);
//var date2 = new Date((mydate1.getMonth()+1)+"/"+mydate1.getDate((mydate1.setDate(mydate1.getDate()+2)))+"/"+mydate1.getFullYear());
////alert(date2);
////mydate2 = new Date();
////expirydate = mydate2.getDate();
//fromToDateCheck(date1,date2);
 
});
</script>

<div style="float:left;">
<h3>Announcements</h3>
<label class="Arial-12-maroon" style="padding-left:35px;">{{msg}}</label>
</div>

<div style="float:right;padding-top:10px;">
{% if user.is_superuser %}
<form method="post" action="." id="listAnnouncement" name="listAnnouncement">
<input name="create" type="submit" id="create" value="Create Announcement" class="b1" onclick="setRedirection('/announcement/create/');" />

</form>
{% endif %}
</div>
<table class="program-blue-box" style="width:100%;padding-left:10px;">
<tr><td style="padding-top:15px;padding-bottom:20px;">
<div style="display:none">
	<select id="id_createddate" name="id_createddate"> 
		{% for each in datevalue %}	
		<option style="width:60px" id = {{each.pk}}>{{each.creation_date|date:"M j, Y"|cut:"Jan 1, 2000"|cut:"Jan 1, 1900"|cut:"None"}}</option>
		{% endfor %}
		</select>
	

</div>
    <ul>
        {% for announcement in announcement_list %}
           <input type = "hidden" id="hdn_announcement_date" value="{{announcement.creation_date}}"/>
		   <input type = "hidden" id="hdn1_announcement_date" value="{{announcement.creation_date|date:"M j, Y"|cut:"Jan 1, 2000"|cut:"Jan 1, 1900"|cut:"None" }}"/>
				
            {% if user.is_superuser %}
				{% if announcement.is_approved and not announcement.is_rejected %}
				 	<li>				
					<a style="text-decoration:none;" href="/announcement/update/?ids={{ announcement.pk }}">
		            <span class="con-grey">{{ announcement.title  }}</span></a>
					<a href="/announcement/delete/?msg=''&ids={{ announcement.pk }}" onclick="return confirm('Are you sure you want to delete?');getQueryValue();">
		            <span>&nbsp;&nbsp;Delete</span></a>
					{% ifequal announcement.display_image 'Show' %}
					<img id = "id_new" class="imgClass" src="/static/css/images/new_icon2.gif" width="15" height="15" style="padding-top:8px"/>
					{% endifequal %}
				  	</li>
				{% else %}
					{% if not announcement.is_approved and not announcement.is_rejected %}
				  	<li>				
					<a style="text-decoration:none;" href="/announcement/update/?ids={{ announcement.pk }}">
		            <span class="con-grey">{{ announcement.title  }}</span></a>
					<label style="">( Waiting for approval )</label>				
					<a href="/announcement/delete/?msg=''&ids={{ announcement.pk }}" onclick="return confirm('Are you sure you want to delete?');getQueryValue();">
		            <span>&nbsp;&nbsp;Delete</span></a>
		        	</li>  
		        	
					{% endif %}
				{% endif %}
        	{% else %}
	    		{% if user == announcement.approved_by %}				
						{% if announcement.is_approved and not announcement.is_rejected %}
						<li>
						<a style="text-decoration:none;" href="/announcement/update/?ids={{ announcement.pk }}">
			            <span class="con-grey">{{ announcement.title  }}</span></a>
						<img src="/static/css/images/new_icon2.gif" class="imgClass" id="id_new" width="15" height="15" style="padding-top:8px"/>
						</li>
						{% endif %}
						
						{% if not announcement.is_approved and not announcement.is_rejected %}
						<li>
						<a style="text-decoration:none;" href="/announcement/update/?ids={{ announcement.pk }}">
			            <span class="con-grey">{{ announcement.title  }}</span></a>
						<label style="">Waiting for approval</label>
						</li>
						{% endif %}

				{% else %}
					{% if announcement.is_approved and not announcement.is_rejected %}
					<li>
					<a style="text-decoration:none;" href="/announcement/view/?ids={{ announcement.pk }}">
		            <span class="con-grey">{{ announcement.title }}</span></a>
					<img id = "id_new" src="/static/css/images/new_icon2.gif" class="imgClass" width="15" height="15" style="padding-top:8px"/> 
					</li>
					{% endif %}
				{% endif %}
			{% endif %}	
		{% endfor %}

		    
	    		{% for key, value in announcement_list.items %}
		
				<li> {{key}} - {{value}}</li>
					
				{% endfor %}

    </ul>

</td></tr>
</table>

{% endblock %}

templates/cvr_table.html
{% extends "cvr/cvr.html" %}
{% load render_table from django_tables2 %}
{% load staticfiles %}

{% block content %}
    {% render_table table %}
    <a href="{% url 'post_new' %}" class="edit">Send</a>
{% endblock %}

templates/domain.html
<script type="application/javascript">
$(function() { 
    $('#overlay #cancel').click(closeOverlay);

    $('#overlay #save' ).click(function(){
        var domain = {
                'project_id': window.location.search.substring('ids').split("=")[1],
                'name':$('#overlay #id_name').val(),
                'domainID':$('#overlay #domainID').val()
              };
        var addDomain = function(json){
            if (json[0].hasOwnProperty('error')){ alert(json[0].error); }
            else{
                $("#id_domain option[value='"+ json[0].id +"']").remove(); 
                $('#id_domain').prepend('<option value="'+json[0].id+'">'+json[0].resource+'</option>');
                closeOverlay();
            }
            }
        $.ajax({ 
            type : "POST",
            url : "/project/domain/",
            data : domain,
            success : addDomain,
            dataType: "json"
            });
        });
    });

</script>
<style>
#overlay label{ color: white; }
</style>
<html>
<head>
    <title> Domain</title>
</head>
<body id="overlay">
    <h3><p><label> Domain </label></p></h3>
    <h4><p><label> {{form.errors}} </label></p></h4>
    {{form.as_p}}
    <div style="padding-left:45px;">
    <input type="hidden" id="domainID" name="domainID" value="{{domainID}}" />
    <input type="button" id="save" name="save" value="save" />
    <input type="button" id="cancel" name="cancel" value="cancel" />
    </div>
</body>
</html>

templates/manage_business_unit.html
{% extends "base.html" %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="/static/css/base.css" title="standard-css1" />
    <link href="/static/css/forms.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block script %}
    <script type="application/javascript" language="JavaScript" src="/static/js/Validation.js"></script>
    <script type="application/javascript" src="/static/js/jquery-1.3.2.min.js"></script>
{% endblock %}

{% block title %} Task {% endblock %}

{% block contentdata %}
    <style>
        form { padding: 10px; }
        .entry-form{ width: 100%; }
        .element{ width: 50%; min-height: 30px; float: left; }
        .label { width: 40%; float: left; }
        .field { width: 60%; float: left; }
        .SaveAndCancel{ width: 100%; clear: both; }
        input[type=text]{ width: 160px;}
        select{ width: 170px; }
        #id_notes{ width: 250px; height: 90px;}
    </style>

    <script>
    $(document).ready(function(){
        $('#cancel').click(function(){
            window.location.href = "/businessunit/list/";
        });
    });
    </script>

    <form id="business_unit_form" name="business_unit_form" action="" method="POST" />
        {% csrf_token %}
        <div class="header">Business Unit</div>
    
        {% if messages %}
            {% for message in messages %}
                <div class="message {{ message.tags }}"><h4>{{ message }}</h4></div>
            {% endfor %}
        {% endif %}

        {{form.errors}}
        <div class="entry-form">
            {% for field in form %}
                <div class="element">
                    <div class="label">{{field.label_tag}}</div><div class="field">{{field}}</div>
                </div>
                {% ifequal field.name 'type' %}
                    {% for address_field in address_form %}
                        <div class="element">
                            <div class="label">{{address_field.label_tag}}</div>
                            <div class="field">{{address_field}}</div>
                        </div>
                    {% endfor %}
                {% endifequal %}
            {% endfor %}
        </div>

        <div class="SaveAndCancel">
            <input type="submit" id="save" name="save" value="save"/>
            <input type="button" id="cancel" name="cancel" value="cancel" />
        </div>
    </form>
{% endblock %}